.PHONY: clean All

All:
	@echo "----------Building project:[ IlkProgram - Debug ]----------"
	@cd "IlkProgram" && "$(MAKE)" -f  "IlkProgram.mk"
clean:
	@echo "----------Cleaning project:[ IlkProgram - Debug ]----------"
	@cd "IlkProgram" && "$(MAKE)" -f  "IlkProgram.mk" clean
